USE [master]
GO

/****** Object:  Database [Greenslate]    Script Date: 11/16/2019 4:44:07 PM ******/
CREATE DATABASE [Greenslate]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Greenslate', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Greenslate.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Greenslate_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Greenslate_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Greenslate] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Greenslate].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Greenslate] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Greenslate] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Greenslate] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Greenslate] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Greenslate] SET ARITHABORT OFF 
GO

ALTER DATABASE [Greenslate] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Greenslate] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Greenslate] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Greenslate] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Greenslate] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Greenslate] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Greenslate] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Greenslate] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Greenslate] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Greenslate] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Greenslate] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Greenslate] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Greenslate] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Greenslate] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Greenslate] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Greenslate] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Greenslate] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Greenslate] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Greenslate] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Greenslate] SET  MULTI_USER 
GO

ALTER DATABASE [Greenslate] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Greenslate] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Greenslate] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Greenslate] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Greenslate] SET  READ_WRITE 
GO


